#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# https://stackoverflow.com/a/5947802/13723015
echo -e "\n${GREEN}PRE COMMIT HOOK TRIGERRED!${NC}"

echo -e "\n${GREEN}LINT STARTED...${NC}\n"
npm run lint:all

if [[ "$?" != 0 ]]; then
  echo -e "\n${RED}LINT FAILED${NC}\n"
  exit 1
fi

echo -e "\n${GREEN}LINT SUCCEEDED!${NC}\n"

echo -e "\n${GREEN}FORMAT STARTED...${NC}\n"
npm run format:all

if [[ "$?" != 0 ]]; then
  echo -e "\n${RED}FORMAT FAILED${NC}\n"
  exit 1
fi

echo -e "\n${GREEN}FORMAT SUCCEEDED!${NC}\n"

echo -e "\n${GREEN}COMMIT SUCCEEDED!${NC}\n"

exit $?

# https://stackoverflow.com/questions/1763156/127-return-code-from
# $? = 127